// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_PIESXeh1pO2zuunGEC8rKYWEHa7dP1E',
    appId: '1:937161589435:web:74cdca6952a5c89d949f9e',
    messagingSenderId: '937161589435',
    projectId: 'smart-photo-app',
    authDomain: 'smart-photo-app.firebaseapp.com',
    storageBucket: 'smart-photo-app.firebasestorage.app',
    measurementId: 'G-1T3TZ5FC24',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjqirOBPG2lPtg4pfpJ2aKs-DJH27PJtk',
    appId: '1:937161589435:android:d0e5e1c5a2feb59b949f9e',
    messagingSenderId: '937161589435',
    projectId: 'smart-photo-app',
    storageBucket: 'smart-photo-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcTOOz0EyM6fZxaD86QFk4Vm-seSIso-U',
    appId: '1:937161589435:ios:feaeefc7f52eb856949f9e',
    messagingSenderId: '937161589435',
    projectId: 'smart-photo-app',
    storageBucket: 'smart-photo-app.firebasestorage.app',
    iosBundleId: 'com.example.smartPhotoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcTOOz0EyM6fZxaD86QFk4Vm-seSIso-U',
    appId: '1:937161589435:ios:feaeefc7f52eb856949f9e',
    messagingSenderId: '937161589435',
    projectId: 'smart-photo-app',
    storageBucket: 'smart-photo-app.firebasestorage.app',
    iosBundleId: 'com.example.smartPhotoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_PIESXeh1pO2zuunGEC8rKYWEHa7dP1E',
    appId: '1:937161589435:web:ca1b9d39dbc34d04949f9e',
    messagingSenderId: '937161589435',
    projectId: 'smart-photo-app',
    authDomain: 'smart-photo-app.firebaseapp.com',
    storageBucket: 'smart-photo-app.firebasestorage.app',
    measurementId: 'G-MV8R5ZYYTP',
  );
}
