// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyDH6oBBSQzulyxS2sCeSR6Ql-aDLRAO3fI",
    authDomain: "smartphotoapp-8f238.firebaseapp.com",
    projectId: "smartphotoapp-8f238",
    storageBucket: "smartphotoapp-8f238.firebasestorage.app",
    messagingSenderId: "357403153157",
    appId: "1:357403153157:web:48ec3ae14ae2020f115d6c",
    measurementId: "G-RMP35MYBFR",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyDH6oBBSQzulyxS2sCeSR6Ql-aDLRAO3fI",
    appId: "1:357403153157:web:48ec3ae14ae2020f115d6c",
    messagingSenderId: "357403153157",
    projectId: "smartphotoapp-8f238",
    storageBucket: "smartphotoapp-8f238.firebasestorage.app",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyDH6oBBSQzulyxS2sCeSR6Ql-aDLRAO3fI",
    appId: "1:357403153157:web:48ec3ae14ae2020f115d6c",
    messagingSenderId: "357403153157",
    projectId: "smartphotoapp-8f238",
    storageBucket: "smartphotoapp-8f238.firebasestorage.app",
    iosBundleId: 'com.example.smartPhotoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: "AIzaSyDH6oBBSQzulyxS2sCeSR6Ql-aDLRAO3fI",
    appId: "1:357403153157:web:48ec3ae14ae2020f115d6c",
    messagingSenderId: "357403153157",
    projectId: "smartphotoapp-8f238",
    storageBucket: "smartphotoapp-8f238.firebasestorage.app",
    iosBundleId: 'com.example.smartPhotoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: "AIzaSyDH6oBBSQzulyxS2sCeSR6Ql-aDLRAO3fI",
    authDomain: "smartphotoapp-8f238.firebaseapp.com",
    projectId: "smartphotoapp-8f238",
    storageBucket: "smartphotoapp-8f238.firebasestorage.app",
    messagingSenderId: "357403153157",
    appId: "1:357403153157:web:32ac20b5c9dbd3a3115d6c",
    measurementId: "G-DCVV115BRK",
  );
}
